name         'mcanevet-hostapd'
version      '0.2.0'
source       'https://github.com/mcanevet/puppet-hostapd'
author       'Mickaël Canévet'
license      'Apache 2.0'
summary      'Puppet hostapd module'
description  'Puppet module for hostapd'
project_page 'https://github.com/mcanevet/puppet-hostapd'
dependency   'puppetlabs/stdlib'
dependency   'theforeman/concat_native'
dependency   'hercules-team/augeasproviders'
